Repository US-EPA-CAMD/easey-monitor-plan-api, pull requests merged in 2020-12, with the labels that each got.

#1 Repo setup
  .github/pull_request-template.md
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: Tech Team

#2 feature/506 Monitor Plan Scaffolding
  .env
  .eslintrc.js
  .gitignore
  .prettierrc
  Dockerfile.dev
  docker-compose.yml
  nest-cli.json
  package-lock.json
  package.json
  src/app.module.ts
  src/config/typeorm.config.ts
  src/main.ts
  src/monitor-plan/monitor-plan.controller.ts
  src/monitor-plan/monitor-plan.module.ts
  src/monitor-plan/monitor-plan.service.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: Emissioners

#3 Feature/506 Added monitor plan DTOs
  src/monitor-plan/dto/link.dto.ts
  src/monitor-plan/dto/monitor-location.dto.ts
  src/monitor-plan/dto/monitor-plan-params.dto.ts
  src/monitor-plan/dto/monitor-plan.dto.ts
  src/monitor-plan/dto/pagination.dto.ts
  src/monitor-plan/entities/monitor-plan.entity.ts
  src/monitor-plan/entities/unit.entity.ts
Labels: Emissioners

#5 feature/498 monitor plan static data
  src/app.module.ts
  src/monitor-plan/dto/monitor-plan-params.dto.ts
  src/monitor-plan/entities/monitor-plan.entity.ts
  src/monitor-plan/entities/unit.entity.ts
  src/monitor-plan/monitor-plan.controller.ts
  src/monitor-plan/monitor-plan.module.ts
  src/monitor-plan/monitor-plan.repository.spec.ts
  src/monitor-plan/monitor-plan.repository.ts
  src/monitor-plan/monitor-plan.service.spec.ts
  src/monitor-plan/monitor-plan.service.ts
Labels: Emissioners

#4 feature/monitor-plan-api-devops-setup
  .env
  .github/workflows/develop-branch.yml
  .github/workflows/feature-branch.yml
  .github/workflows/release-branch.yml
  .github/workflows/staging-deployment.yml
  .github/workflows/test-deployment.yml
  .gitignore
  README.md
  docker-compose.yml
  manifest-vars.dev.yml
  manifest-vars.staging.yml
  manifest-vars.test.yml
  manifest.yml
  sonar-project.properties
  src/app.module.ts
  src/config/app.config.ts
  src/config/db.config.ts
  src/config/typeorm.config.ts
  src/main.ts
  src/monitor-location/monitor-location.controller.ts
  src/monitor-location/monitor-location.module.ts
  src/monitor-location/monitor-location.service.ts
  src/monitor-plan/monitor-plan.controller.ts
  src/monitor-plan/monitor-plan.service.ts
Labels: DevOps, Emissioners, Tech Team

#6 feature/498 link headers
  src/monitor-plan/dto/monitor-plan-params.dto.ts
  src/monitor-plan/monitor-plan.controller.ts
  src/monitor-plan/monitor-plan.repository.ts
  src/monitor-plan/monitor-plan.service.spec.ts
  src/monitor-plan/monitor-plan.service.ts
Labels: Emissioners

#8 Monitoring Mehods
  package-lock.json
  package.json
  src/app.module.ts
  src/dtos/monitor-method.dto.ts
  src/entities/monitor-location.entity.ts
  src/entities/monitor-method.entity.ts
  src/entities/monitor-plan.entity.ts
  src/entities/unit.entity.ts
  src/maps/base.map.ts
  src/maps/monitor-method.map.ts
  src/monitor-location/monitor-location.controller.ts
  src/monitor-plan/monitor-plan.controller.ts
  src/monitor-plan/monitor-plan.repository.ts
  src/monitoring-method/monitoring-method.controller.ts
  src/monitoring-method/monitoring-method.module.ts
  src/monitoring-method/monitoring-method.repository.ts
  src/monitoring-method/monitoring-method.service.ts
  src/routes.ts
Labels: Emissioners
