Repository US-EPA-CAMD/easey-monitor-plan-api, pull requests merged in 2021-09, with the labels that each got.

#76 add POST analyzer-range
  src/analyzer-range-workspace/analyzer-range.controller.ts
  src/analyzer-range-workspace/analyzer-range.service.ts
Labels: Emissioners

#77 Feature/1733 edit systems data
  src/monitor-system-workspace/monitor-system.controller.ts
  src/monitor-system-workspace/monitor-system.service.ts
Labels: Emissioners

#79 create monitor-system-data
  src/monitor-system-workspace/monitor-system.controller.ts
  src/monitor-system-workspace/monitor-system.service.ts
Labels: Emissioners

#80 Feature/1775 create new system component
  src/component-workspace/component.service.ts
  src/dtos/component-update.dto.ts
  src/system-component-workspace/system-component.controller.ts
  src/system-component-workspace/system-component.module.ts
  src/system-component-workspace/system-component.service.ts
  src/system-component/system-component.module.ts
Labels: Emissioners

#81 Feature/1776 edit system component
  src/system-component-workspace/system-component.controller.ts
  src/system-component-workspace/system-component.service.ts
Labels: Emissioners

#82 Feature/1776 edit system component
  src/system-component-workspace/system-component.controller.ts
  src/system-component-workspace/system-component.service.ts
Labels: Emissioners

#83 fix bug related to 1775, 1802 and update-fuel-flow
  src/dtos/update-monitor-system-component.dto.ts
  src/entities/monitor-system.entity.ts
  src/system-component-workspace/system-component.repository.ts
  src/system-component-workspace/system-component.service.ts
  src/system-fuel-flow-workspace/system-fuel-flow.service.ts
Labels: Emissioners

#84 change to workspace repository
  src/system-fuel-flow-workspace/system-fuel-flow.repository.ts
Labels: bug

#87 add POST monitor-span-data
  src/monitor-span-workspace/monitor-span.controller.ts
  src/monitor-span-workspace/monitor-span.service.ts
Labels: Emissioners

#88 Feature/629 view monitoring span
  src/monitor-span-workspace/monitor-span.controller.ts
  src/monitor-span-workspace/monitor-span.repository.ts
  src/monitor-span-workspace/monitor-span.service.ts
Labels: Emissioners

#89 add PUT monitor-span-data
  src/monitor-span-workspace/monitor-span.controller.ts
  src/monitor-span-workspace/monitor-span.service.ts
Labels: Emissioners

#91 add PUT edit-monitor-default
  src/monitor-default-workspace/monitor-default.controller.ts
  src/monitor-default-workspace/monitor-default.repository.ts
  src/monitor-default-workspace/monitor-default.service.ts
Labels: Emissioners

#93 map scaleTransitionPoint to maxLowRange
  src/dtos/monitor-span-base.dto.ts
  src/entities/monitor-span.entity.ts
  src/entities/workspace/monitor-span.entity.ts
  src/monitor-span-workspace/monitor-span.service.ts
Labels: Emissioners

#95 fix monitor-span-map scalaTransitionPoint
  src/maps/monitor-span.map.spec.ts
  src/maps/monitor-span.map.ts
Labels: Emissioners

#90 Feature/2029 monitor plan api auth guard
  package-lock.json
  package.json
  src/analyzer-range-workspace/analyzer-range.controller.ts
  src/config/app.config.ts
  src/decorators/current-user.decorator.ts
  src/guards/auth.guard.spec.ts
  src/guards/auth.guard.ts
  src/interceptors/current-user.interceptor.ts
  src/main.ts
  src/mats-method-workspace/mats-method.controller.ts
  src/monitor-method-workspace/monitor-method.controller.ts
  src/monitor-plan-workspace/monitor-plan.controller.ts
  src/monitor-plan-workspace/monitor-plan.module.ts
  src/monitor-system-workspace/monitor-system.controller.ts
  src/system-component-workspace/system-component.controller.ts
  src/system-fuel-flow-workspace/system-fuel-flow.controller.ts
  src/utils.spec.ts
  src/utils.ts
Labels: Emissioners, Tech Team

#97 Feature/2029 monitor auth guard
  src/guards/auth.guard.ts
Labels: Emissioners, Tech Team

#98 Feature/1705 edit mp formula
  src/guards/auth.guard.ts
  src/monitor-formula-workspace/monitor-formula.controller.spec.ts
  src/monitor-formula-workspace/monitor-formula.controller.ts
  src/monitor-formula-workspace/monitor-formula.module.ts
  src/monitor-formula-workspace/monitor-formula.repository.ts
  src/monitor-formula-workspace/monitor-formula.service.spec.ts
  src/monitor-formula-workspace/monitor-formula.service.ts
Labels: Emissioners

#99 fix bug with endDate not updating
  src/maps/monitor-default.map.ts
  src/monitor-default-workspace/monitor-default.service.ts
Labels: bug

#100 Feature/1710 load post endpoint
  src/monitor-load-workspace/monitor-load.controller.spec.ts
  src/monitor-load-workspace/monitor-load.service.spec.ts
  src/monitor-load-workspace/monitor-load.service.ts
Labels: Emissioners

#101 Bug/2006 fix edit system type
  src/monitor-system-workspace/monitor-system.service.ts
Labels: Emissioners

#102 Bug/2006 fix edit system type
  src/monitor-system-workspace/monitor-system.service.ts
Labels: Emissioners

#103 Feature/auth-ip-changes
  src/guards/auth.guard.ts
Labels: Emissioners, Tech Team
