Repository US-EPA-CAMD/easey-monitor-plan-api, pull requests merged in 2021-06, with the labels that each got.

#41 Merge for PI-4 Sprint 4 508 Testing
  package-lock.json
  package.json
  src/app.module.ts
  src/dtos/monitor-formula.dto.ts
  src/dtos/monitor-load.dto.ts
  src/dtos/monitor-span.dto.ts
  src/entities/monitor-formula.entity.ts
  src/entities/monitor-load.entity.ts
  src/entities/monitor-span.entity.ts
  src/maps/monitor-formula.map.ts
  src/maps/monitor-load.map.ts
  src/maps/monitor-span.map.ts
  src/monitor-formula/monitor-formula.controller.ts
  src/monitor-formula/monitor-formula.module.ts
  src/monitor-formula/monitor-formula.repository.ts
  src/monitor-formula/monitor-formula.service.spec.ts
  src/monitor-formula/monitor-formula.service.ts
  src/monitor-load/monitor-load.controller.ts
  src/monitor-load/monitor-load.module.ts
  src/monitor-load/monitor-load.repository.ts
  src/monitor-load/monitor-load.service.spec.ts
  src/monitor-load/monitor-load.service.ts
  src/monitor-span/monitor-span.controller.ts
  src/monitor-span/monitor-span.module.ts
  src/monitor-span/monitor-span.repository.ts
  src/monitor-span/monitor-span.service.spec.ts
  src/monitor-span/monitor-span.service.ts
  src/routes.ts
Labels: Tech Team

#43 feature/1487-add-fuel-code-to-system-fuels
  src/dtos/monitor-system.dto.ts
  src/dtos/system-fuel-flow.dto.ts
  src/entities/monitor-system.entity.ts
  src/entities/system-fuel-flow.entity.ts
  src/maps/monitor-system.map.ts
  src/maps/system-fuel-flow.map.ts
  src/monitor-system/monitor-system.service.ts
  src/monitor-system/system-fuel-flow.repository.ts
Labels: Emissioners

#42 Feature/1416 check out api endpoint
  package-lock.json
  package.json
  src/config/app.config.ts
  src/config/db.config.ts
  src/config/typeorm.config.ts
  src/dtos/component.dto.ts
  src/dtos/monitor-plan.dto.ts
  src/dtos/user-check-out.dto.ts
  src/entities/analyzer-range.entity.ts
  src/entities/component.entity.ts
  src/entities/monitor-location.entity.ts
  src/entities/monitor-method.entity.ts
  src/entities/monitor-plan.entity.ts
  src/entities/unit.entity.ts
  src/entities/user-check-out.entity.ts
  src/main.ts
  src/monitor-location/monitor-location.controller.ts
  src/monitor-location/monitor-location.repository.ts
  src/monitor-location/monitor-location.service.ts
  src/monitor-location/unit-op-status.repository.ts
  src/monitor-method/monitor-method.service.ts
  src/monitor-plan/monitor-plan.controller.ts
  src/monitor-plan/monitor-plan.module.ts
  src/monitor-plan/monitor-plan.repository.spec.ts
  src/monitor-plan/monitor-plan.repository.ts
  src/monitor-plan/monitor-plan.service.spec.ts
  src/monitor-plan/monitor-plan.service.ts
  src/monitor-plan/user-check-out.repository.ts
  src/monitor-system/monitor-system.controller.ts
  src/monitor-system/monitor-system.repository.ts
  src/monitor-system/monitor-system.service.ts
  src/routes.ts
  src/supplemental-methods/supplemental-methods.service.ts
Labels: Emissioners

#44 POST /:id/check-out returns check-out record
  src/monitor-plan/monitor-plan.controller.ts
  src/monitor-plan/monitor-plan.service.ts
  src/monitor-plan/user-check-out.repository.ts
Labels: Emissioners

#45 update check-out expiration to lock-activity
  src/entities/user-check-out.entity.ts
  src/monitor-plan/monitor-plan.controller.ts
  src/monitor-plan/monitor-plan.service.ts
  src/monitor-plan/user-check-out.repository.ts
Labels: Emissioners

#47 feature/1344-add-method-id-to-api-response
  src/dtos/monitor-method.dto.ts
  src/maps/monitor-method.map.ts
  src/monitor-method-workspace/monitor-method.service.ts
Labels: Emissioners

#48 add unit tests for monitor-plan.service
  src/monitor-plan-workspace/monitor-plan.controller.ts
  src/monitor-plan-workspace/monitor-plan.service.spec.ts
  src/monitor-plan-workspace/monitor-plan.service.ts
Labels: Emissioners

#49 Feature/1344 edit monitoring methods
  package-lock.json
  package.json
  src/component/component.controller.spec.ts
  src/dtos/update-monitor-method.dto.ts
  src/entities/monitor-location.entity.ts
  src/maps/monitor-location.map.ts
  src/maps/monitor-plan.map.ts
  src/monitor-location/monitor-location.module.ts
  src/monitor-method-workspace/monitor-method.controller.ts
  src/monitor-method-workspace/monitor-method.module.ts
  src/monitor-method-workspace/monitor-method.repository.ts
  src/monitor-method-workspace/monitor-method.service.ts
  src/monitor-plan-workspace/monitor-plan.controller.ts
  src/monitor-plan-workspace/monitor-plan.service.spec.ts
  src/monitor-plan-workspace/monitor-plan.service.ts
  src/monitor-plan-workspace/user-check-out.repository.ts
  src/monitor-plan/monitor-plan.controller.ts
  src/monitor-plan/monitor-plan.service.ts
  src/routes.ts
Labels: Emissioners

#50 add check-in endpoint, update monitor-location route
  src/monitor-method-workspace/monitor-method.repository.ts
  src/monitor-plan-workspace/monitor-plan.controller.ts
  src/monitor-plan-workspace/monitor-plan.service.ts
  src/routes.ts
Labels: Emissioners

#51 fix updateMethod bug
  src/monitor-method-workspace/monitor-method.service.ts
Labels: bug
